[package]
name = "godwoken-types"
version = "0.1.0-pre"
authors = ["Jiang Jinyang <jjyruby@gmail.com>"]
edition = "2018"
license = "MIT"

[features]
default = ["std"]
std = []

[dependencies]
molecule = { path = "../molecule/bindings/rust", default-features = false }
