name: Rust

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install rust components
      run: rustup component add rustfmt && rustup component add clippy
    - name: Install rust riscv target
      run: rustup target add riscv64imac-unknown-none-elf
    - name: Update submodules
      run: git submodule update --init
    - name: Run CI checks
      run: make ci
